name: Auto Thing
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: dice-roll
      run: echo "PROCEED=$((RANDOM%20))" >> $GITHUB_ENV
      shell: bash
      
    - if: env.PROCEED > '1'
      name: Cancelling
      uses: andymckay/cancel-action@0.2
      
    - if: env.PROCEED > '1'
      name: Waiting for cancellation
      run: sleep 60

  date:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: save current date
        run: |
          date > time.txt

      - name: setup git config
        run: |
          git config user.name "ksatia"
          git config user.email "ksatia@gmail.com"

      - name: commit
        run: |
          git add time.txt
          git commit -m "new date commit"
          git push origin main
